version: "3.8"

services:
  service1:
    build: ./service1
    container_name: service1
    expose:
      - "8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 20s

  service2:
    build: ./service2
    container_name: service2
    expose:
      - "8002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 20s

  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      service1:
        condition: service_healthy
      service2:
        condition: service_healthy
